### PR TITLE
fix send, fix lost data before connect open, add example.

### PR DESCRIPTION
**Pull request by Lyoko-Jeremie**
## important change is send returning from cold Observable to third mode

1(Direct) send and return true or false (false when socket is not open)
2(Promise) send and return promise
3(Observable) send and return cold Observable

the default mode is 3(Observable).

and that, import bluebird to support Promise.

### CODE REVIEW

**Comment by bomberblue07** [comment]
@Lyoko-Jeremie The only thing I would fix is that you reference your own fork in the package.json, not this one.

Slightly related: It just hit me, but shouldn't the dependencies on angular be peer dependencies? It's a waste of bandwidth to download those libs again when the client application likely already has them.

**Comment by afrad** [comment]
Thank you. Could you please update Readme?

**Comment by bomberblue07** [comment]
@afrad What's missing from the readme? He updated it with the new send modes.

**Comment by afrad** [comment]
Sorry oversaw it. Great, thank you.

**Comment by Lyoko-Jeremie** [comment]
Oh, Thanks for yours work.
  
and i find some error in the example
```
ws.send("this will be send and return Observer.").subscribe(
```
may be change to
```
ws.send("this will be send and return Observer.", WebSocketSendMode.Observable).subscribe(
```

**Comment by Lyoko-Jeremie** [comment]
and i think that
when use flatmap in observer mode
return next may good than return complete
so, maybe add 4th mode to return old observer ?
@afrad 
^_^

**Comment by afrad** [comment]
Looks interesting. Could you please create a PR?

**Comment by bomberblue07** [comment]
@afrad can you please push up the current version to NPM in the meantime? Thanks in advance!

**Comment by afrad** [comment]
done

**Pull request merged**
